# Generated by Django 3.2 on 2023-05-22 14:14

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230520_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[api.validators.validate_cooking_time], verbose_name='Время приготовления'),
        ),
    ]
