# Generated by Django 3.2 on 2023-05-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow_check_self_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
