# Generated by Django 3.2 on 2023-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=256, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
